### PR TITLE
LRDOCS-10287 tutorial code and article fixes

### PR DESCRIPTION
**Pull request by JamesAGarcia**
This PR includes multiple tutorial fixes, per [LRDOCS-10287](https://issues.liferay.com/browse/LRDOCS-10287).

### CODE REVIEW

**Comment by sez11a** [comment]
Hey @JamesAGarcia yes, you should send the code to BChan first.

**Comment by JamesAGarcia** [comment]
@sez11a Code edits are in review here: https://github.com/brianchandotcom/liferay-learn/pull/364

**Comment by sez11a** [comment]
@JamesAGarcia Okay; I'll hold off until after@brianchandotcom reviews the code.

**Comment by JamesAGarcia** [comment]
@sez11a I forgot to mention: as mentioned in our Monday meeting, this PR is ready for review.

**Comment by sez11a** [comment]
Rebased and pushed (with no changes). Thanks!

**Pull request closed without merging**
