### PR TITLE
search 7.4 | upgrading search for 7.4 | LRDOCS-9736

### PR DESCRIPTION
**Pull request by rbohl**
Updates to the upgrading search documentation:
* Remove 7.3 as the newest version and update versions in general
* Remove a confusing table that had a lot of repeated information
* Cover the migration of search tuning indexes into the liferay db
* Other stuff...
https://issues.liferay.com/browse/LRDOCS-9736
cc @lipusz

Added work for https://issues.liferay.com/browse/LRDOCS-9499 on 11/16/2021

### CODE REVIEW

**Comment by rbohl** [comment]
Rich, I likely need to touch many of the same files for  https://issues.liferay.com/browse/LRDOCS-9499. I'll add them in commits to this branch. cc @lipusz

**Comment by rbohl** [comment]
I've done what I wanted for LRDOCS-9499 and I rebased on master due to Jim's mass admonition refactor. It _should_ be good to go now, Rich! cc @lipusz

**Comment by sez11a** [comment]
@rbohl , any chance you can remove the .rst files and convert this to MyST? Any modifications should include that conversion.

**Comment by rbohl** [comment]
Sure, stand by.

**Comment by rbohl** [comment]
Okay, I think I got it, plus some additional cleanup.

**Comment by sez11a** [comment]
Superseded by https://github.com/rbohl/liferay-learn/pull/108

**Pull request closed without merging**
