### PR TITLE
LRDOCS-7726 Liferay JS Generator Batch 01 Port

### PR DESCRIPTION
**Pull request by mwilliams2014**
Supersedes https://github.com/sez11a/liferay-learn/pull/24

### CODE REVIEW

**Comment by mwilliams2014** [comment]
Need to update examples to follow template. Pushing updates later today.

**Comment by mwilliams2014** [comment]
I'll see what state this in later today. I believe it's close to done, if not done...

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by sez11a** [comment]
Wordsmithed, but projects don't work. Superseded by https://github.com/ethanbustad/liferay-learn/pull/1

**Pull request closed without merging**
