### PR TITLE
search 7.x | synonym filters | LRDOCS-7365

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-7365
cc @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
Hello Folks, @rbohl @sez11a 

Do you have any news on this? :newspaper: 

Thanks,
Tibor

**Comment by lipusz** [comment]
Bump!

**Comment by rbohl** [comment]
@jrhoun this one, while maybe not a super-urgent-liferay-will-fail-if-we-delay topic, was prioritized because of a request from the Big Canadian Liferay Customer wanting to configure french language synonyms. Bugs were fixed, code was backported, and docs were written, but the docs have stalled here (for understandable reason). If you're still poaching from @sez11a's queue maybe this one could be pushed forward?

**Comment by rbohl** [comment]
Wait a second, @lipusz, we the availability as 7.2 FP 12 and 7.3 FP2, neither of which are yet released. Do we really need to prioritize this?

**Comment by lipusz** [comment]
Good catch, Russ. I got lost tracking the backports and I thought it was included in FP1. I forgot about this note and the future fix packs.

**Comment by jrhoun** [comment]
Going to take a look at this now.

**Comment by jrhoun** [comment]
Merged. Thanks.

@sez11a can close this one.

**Pull request closed without merging**
