### PR TITLE
LRDOCS-9460 Xuggler Deprecation, Replaced with FFmpeg

### PR DESCRIPTION
**Pull request by JamesAGarcia**
This PR includes revisions to existing documentation on Xuggler, per [LRDOCS-9460](https://issues.liferay.com/browse/LRDOCS-9460). It also includes some general revisions for other external services documentation (e.g., ImageMagick, Ghostscript).

### CODE REVIEW

**Comment by JamesAGarcia** [comment]
@sez11a I resolved the merge conflict using the Github UI (for the first time), and it added a merge commit. Is this acceptable? I assumed you could remove it during wordsmithing?

**Comment by sez11a** [comment]
@JamesAGarcia probably not a good idea, but I'll check.

**Comment by sez11a** [comment]
@JamesAGarcia Nope, that doesn't work. You still get merge conflicts when you rebase with master.

**Comment by JamesAGarcia** [comment]
Good to know! I believe I fixed the issue. Just let me know if you're still getting the merge conflict.

**Comment by sez11a** [comment]
Superseded by https://github.com/jrhoun/liferay-learn/pull/1161

**Pull request closed without merging**
