### PR TITLE
LRDOCS 8143 Workflow Designer (again)

### PR DESCRIPTION
**Pull request by justinchoi001**

### CODE REVIEW

**Comment by sez11a** [comment]
Hey @justinchoi001 this is merge conflicted.

**Comment by justinchoi001** [comment]
@sez11a , I've resolved the conflicts.

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by sez11a** [comment]
Superseded by https://github.com/justinchoi001/liferay-learn/pull/38

**Pull request closed without merging**
