### PR TITLE
LRDOCS-7927 Cluster example simplified

### PR DESCRIPTION
**Pull request by jhinkey**
I paired it down a lot. I hope this does the trick. ;-)
https://issues.liferay.com/browse/LRDOCS-7927

cc/ @rbohl

### CODE REVIEW

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by sez11a** [comment]
Hey @jhinkey this is merge conflicted on images. I don't know which ones are the right ones.

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by jhinkey** [comment]
superceded by https://github.com/sez11a/liferay-learn/pull/127

**Pull request closed without merging**
