### PR TITLE
Segments and Roles | 7.2 DXP(SP2/SP3)/7.3 GA2 | LPS-110106

### PR DESCRIPTION
**Pull request by rbohl**
I wrote just one section of this (Assigning Site Roles to Segments), but did some editing work, reorganization, added links, and made it appear in the navigation as well. This will be an ongoing effort as more work gets done on this feature. cc @mwilliams2014 @dejuknow

### CODE REVIEW

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by rbohl** [comment]
Are you sure you're not looking for this one :wink: : https://github.com/sez11a/liferay-learn/pull/42

**Comment by rbohl** [comment]
Oh I see, this one is even earlier! Carry on then.

**Comment by sez11a** [comment]
Superseded by https://github.com/jrhoun/liferay-learn/pull/465

**Pull request closed without merging**
