### PR TITLE
LRDOCS-8043 Move and add links to updating Liferay Portal CE

### PR DESCRIPTION
**Pull request by jhinkey**
https://issues.liferay.com/browse/LRDOCS-8043

I moved the article to the Upgrade Basics section and inserted a sym link to it in the Maintaining Liferay section (the parent section of Patching Liferay).

And I updated the articles in response to the concerns brought up in the Blog post comments.

cc/ @achaparro

### CODE REVIEW

**Comment by jhinkey** [comment]
@sez11a I pushed a commit that mentions migrating your `data/` folder to the new installation.

**Comment by jhinkey** [comment]
@sez11a I addressed all of the issues that Max brought up.

**Comment by sez11a** [comment]
@jhinkey That's a lot of new commits. Are you sure you're done? ;-)

**Comment by jhinkey** [comment]
Closing this. I want Alberto to review it first.

**Pull request closed without merging**
