### PR TITLE
LRDOCS-7542 fragments dev batch 1 redo

### PR DESCRIPTION
**Pull request by mwilliams2014**
@sez11a here are the updates per your comments. Please let me know if you think anything else needs updated. Thanks!

### CODE REVIEW

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by sez11a** [comment]
Hey @mwilliams2014 can you create an .rst file so I can see the proper order of these articles? Thanks!

**Comment by mwilliams2014** [comment]
@sez11a updated. I think I did it right. Please let me know if anything needs changed. Thx!

**Comment by sez11a** [comment]
@mwilliams2014 Not the READMEs. Those are only for GitHub and are pointless (and we won't be using them permanently). The real .rst is the one named for the folder (i.e., `developing-page-fragments.rst`) and exist in the folder above where the articles are.

**Comment by mwilliams2014** [comment]
@sez11a ah, ok. I'll redo it.

**Comment by mwilliams2014** [comment]
@sez11a RSTs updated

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by sez11a** [comment]
Superseded by https://github.com/mwilliams2014/liferay-learn/pull/9

**Pull request closed without merging**
