### PR TITLE
LRDOCS-7953 Fundamentals > Understanding Module Projects

### PR DESCRIPTION
**Pull request by jhinkey**
https://issues.liferay.com/browse/LRDOCS-7953

### CODE REVIEW

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by jhinkey** [comment]
superseded by https://github.com/sez11a/liferay-learn/pull/89

**Comment by sez11a** [comment]
@jhinkey Not sure you noticed the reviewing comment above your closing of this PR. I completed wordsmithing this on Friday and saw that you'd closed it. Since it was late in the day, I called it a day. I will try merging your other branch into mine, but depending on how difficult that is, I may ask you to resolve.

**Comment by sez11a** [comment]
Merged: 
0f66934d..af027cd3  master -> master

**Comment by jhinkey** [comment]
I'd noticed that you were reviewing it but thought by in our Slack chat that you were asking me to make the "metadata" correction. I didn't know you'd wordsmithed.

Yes, if there's difficulties merging, I'll be happy to do the merge.

**Comment by sez11a** [comment]
No; I was just letting you know as I was wordsmithing it. Since that was the only change in the other PR, I closed that one and went with this one.

**Pull request closed without merging**
