### PR TITLE
LRDOCS-9267 Introduction to Product Groups (New Article)

### PR DESCRIPTION
**Pull request by aswinrajeevofficial**
This PR contains the new article on Product Groups.

JIRA: https://issues.liferay.com/browse/LRDOCS-9267

### CODE REVIEW

**Comment by sez11a** [comment]
@aswinrajeevofficial Somehow, a new article is being reported as having a conflict. :man_shrugging:

**Comment by aswinrajeevofficial** [comment]
Hey @sez11a, it looks like the changes for the article were already put in through another commit. See [here](https://github.com/liferay/liferay-learn/commit/29c9707cafcefff110c2294cc5d5e20b9ccba438#diff-f37c39510e4d5dbf2087a09137306412eff6369bb075e4d59b21615a0ccceb64).

**Comment by aswinrajeevofficial** [comment]
Hi @sez11a, I've pulled in the changes from master and made your changes on top of it. There were 10 images to be added along with a couple of admonitions, which were missing. I added those as well.

**Comment by sez11a** [comment]
Hey @aswinrajeevofficial this one is also still showing merge conflicts. I looked at the commit list in this pull, and I don't see my commit in the list. So something weird seems to be going on. I know I wordsmithed this file in another pull; my guess is you didn't intend this file to be in that pull? At this point, you'll have to start with a copy of what's in master and make your modifications to that. 
```
(LRDOCS-9267-Document-Product-Groups $) $ git rebase master
Auto-merging docs/commerce/latest/en/promoting-products/introduction-to-product-groups.md
CONFLICT (content): Merge conflict in docs/commerce/latest/en/promoting-products/introduction-to-product-groups.md
error: could not apply 3d3ae54c4... LRDOCS-9267 Introduction to Product Groups
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 3d3ae54c4... LRDOCS-9267 Introduction to Product Groups
```

**Comment by aswinrajeevofficial** [comment]
Hi @sez11a, 
I just fixed all the merge conflicts for all the pulls. This article's wordsmithing was done by you in another commit. This was done 6 days ago. I see it on the feature branch as well as on the master branch.

**Comment by sez11a** [comment]
Rebased and pushed; thanks!

**Pull request closed without merging**
