### PR TITLE
LRDOCS-8508 Rendering Views with MVC Portlet

### PR DESCRIPTION
**Pull request by jhinkey**
https://issues.liferay.com/browse/LRDOCS-8508

### CODE REVIEW

**Comment by sez11a** [comment]
@jhinkey This has a merge conflict; please fix. Thanks!

**Comment by jhinkey** [comment]
It's deconflicted now. Thanks, @sez11a !

**Comment by sez11a** [comment]
Rebased and pushed; thanks!

**Comment by jhinkey** [comment]
Thanks for the wordsmithing, Rich!

**Pull request merged**
