### PR TITLE
LRDOCS-10088 API Tutorial Dependency

### PR DESCRIPTION
**Pull request by mtokudome**
https://issues.liferay.com/browse/LRDOCS-10088

### CODE REVIEW

**Comment by sez11a** [comment]
@mtokudome Doesn't the .jar file change depending on the API?

**Comment by mtokudome** [comment]
Yes, I would change the link appropriately for each tutorial. Sorry I have `com.liferay.headless.admin.user.client.jar` for this sample but that would be for UserAccount API or Accounts API, etc. For this Document API, I would use `com.liferay.headless.delivery.client.jar`(and so forth for each API tutorial).

**Comment by mtokudome** [comment]
@sez11a this is ready for review

**Comment by sez11a** [comment]
Superseded by https://github.com/mtokudome/liferay-learn/pull/36

**Pull request closed without merging**
