### PR TITLE
LRDOCS-7915 & LRDOCS-8031: Port 7.3 Breaking Changes

### PR DESCRIPTION
**Pull request by mwilliams2014**

### CODE REVIEW

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by sez11a** [comment]
Merge conflicted.

**Comment by mwilliams2014** [comment]
I'll take a look ;-)

**Comment by mwilliams2014** [comment]
@sez11a merge conflict fixed and [LRDOCS-8031](https://issues.liferay.com/browse/LRDOCS-8031) updates included here as well.

**Comment by sez11a** [comment]
Just started reviewing :)

**Pull request merged**
