### PR TITLE
LRDOCS-7536 page fragment user guide

### PR DESCRIPTION
**Pull request by mwilliams2014**
Supersedes https://github.com/mwilliams2014/liferay-learn/pull/10

### CODE REVIEW

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by sez11a** [comment]
Hey @mwilliams2014 can you rebase this on master and resend? Skip the first conflict on the Commerce tutorial; that's what caused all those merge commits in this branch. I have since fixed this in my master, but the rest of the conflicts are the files here. Thanks!

**Comment by mwilliams2014** [comment]
OK. Will do. Thanks

**Comment by mwilliams2014** [comment]
@sez11a  Superseded by https://github.com/sez11a/liferay-learn/pull/43

**Pull request closed without merging**
