### PR TITLE
search 7.3 | securing elasticsearch improvements | LRDOCS-8667

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-8667
cc @lipusz

### CODE REVIEW

**Comment by rbohl** [comment]
@lipusz we may need an update:

WRONG?
To generate certificates and keys in PEM format run

```
./bin/elasticsearch-certutil cert --pem --ca-cert config/certs/ca.crt --ca-key config/certs/ca.key --dns localhost --ip 127.0.0.1 --name elastic-nodes
```
[We don't have a ca.crt and ca.key because we didn't use a PEM CA this time]

RIGHT?
To generate certificates and keys in PEM format run

```
 ./bin/elasticsearch-certutil cert --pem config/certs/elastic-stack-ca.p12 --dns localhost --ip 127.0.0.1 --name elastic-nodes
```
generates a `certificate-bundle.zip` with these contents:

├── ca
│   └── ca.crt
└── elastic-nodes
    ├── elastic-nodes.crt
    └── elastic-nodes.key

**Comment by lipusz** [comment]
@rbohl Thanks for catching it. However, your command is also missing some parts to be correct: the `--ca` option and the `-ca-pass liferay` part. The correct commands are:

1. To generate CA cert and private key in PEM format:
    ```
    ./bin/elasticsearch-certutil ca --pem --ca-dn CN=elastic-ca
    ```
1. To generate node cert in PEM format using PEM format CA:
    ```
    ./bin/elasticsearch-certutil cert --pem --ca-cert config/certs/ca.crt --ca-key config/certs/ca.key --dns localhost --ip 127.0.0.1 --name elastic-nodes
    ```
1. To generate CA cert and private key in PKCS#12 format:
   ```
     ./bin/elasticsearch-certutil ca --ca-dn CN=elastic-ca
   ```
1. To generate node cert in PEM format using PKCS#12 format CA:
    ```
    ./bin/elasticsearch-certutil cert --pem --ca config/certs/elastic-stack-ca.p12 --ca-pass liferay --dns localhost --ip 127.0.0.1 --name elastic-nodes
    ```
1. To generate node cert in PKCS#12 format using PKCS#12 format CA:
    ```
         ./bin/elasticsearch-certutil cert --ca config/certs/elastic-stack-ca.p12 --ca-pass liferay --dns localhost --ip 127.0.0.1 --name elastic-nodes
    ```

Tested.

**Comment by lipusz** [comment]
@rbohl Could you forward this to JR? I'd like to have published as soon as possible. Thanks!

**Comment by rbohl** [comment]
I think the first step would be to ask @sez11a if he'll have time to get to it soon. We haven't previously flagged this as urgent to him, I don't believe.

Rich, this PR updates existing docs that were initially published while I was away, and they needed some pretty serious cleanup, correction, and additions (as usual in Search, the only consistent thing is that everything is always changing). Is it possible to prioritize it?

**Comment by sez11a** [comment]
Superseded by https://github.com/jrhoun/liferay-learn/pull/841

**Pull request closed without merging**
