### PR TITLE
(MFA) LRDOCS-7697 SME edits (vol.1)

### PR DESCRIPTION
**Pull request by lipusz**
Hey Rich,

Here are my first edits, see just my changes: https://github.com/lipusz/liferay-learn/compare/c8ade78b786d60579c25de6b0f1f62a659251e42...LRDOCS-7697_LRDOCS-7699-mfa

I'm going to go through the tech-docs tickets as a next step to see if there are other important details we should include. However, your draft seemed to be complete, I did not feel that we may be missing something. Thanks! :+1: 

Regards,
Tibor

/cc @zsigmondrab
/cc @martamedio

### CODE REVIEW

**Comment by lipusz** [comment]
@sez11a Hint: you may want to enable https://grow.liferay.com/excellence/OriginAl on your liferay-learn fork too. ;-)

**Comment by lipusz** [comment]
Hold on, I have accidentally screwed up my branches...

**Comment by lipusz** [comment]
Fixed.

**Comment by sez11a** [comment]
Thank you, @lipusz ! Superseded by https://github.com/jrhoun/liferay-learn/pull/693

**Pull request closed without merging**
