### PR TITLE
System Settings | LRDOCS-7588

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-7588

### CODE REVIEW

**Comment by sez11a** [comment]
This has a merge conflict.

**Comment by rbohl** [comment]
That's interesting, because it doesn't look like that file exists in your master branch :man_shrugging:

**Comment by rbohl** [comment]
I guess it used to, because the diff shows https://github.com/sez11a/liferay-learn/pull/9/commits/550a0e1837eb4cb7c50952838a3b652e01d08c80

So someone deleted the section and the README?

**Comment by rbohl** [comment]
Maybe [this](https://github.com/sez11a/liferay-learn/commit/02d83ef48cdf2a92bc34641d545079f8dcba591c#diff-508e016156f2037995a46d6a1bebe6f9) is the cause? It was renamed to filestorage/README.rst 9 days ago (same day I sent the PR)? I'm not sure why it would have been renamed. Let me know how you'd like me to proceed.

**Comment by rbohl** [comment]
Okay, I think I have it deconflicted locally. Resending.

**Comment by rbohl** [comment]
Superseded: https://github.com/sez11a/liferay-learn/pull/17

**Pull request closed without merging**
