### PR TITLE
LRDOCS-8471 - Building Forms with Conditional Fields

### PR DESCRIPTION
**Pull request by justinchoi001**
cc @rbohl

### CODE REVIEW

**Comment by rbohl** [comment]
Hey Justin, how did we define the need for this article? I don't see that it adds so much value that the information shouldn't just be incorporated into the introduction of the very similar [Form Rules Overview](https://learn.liferay.com/dxp/7.x/en/process-automation/forms/user-guide/advanced-forms-usage/form-rules/form-rules-overview.html)?

**Comment by justinchoi001** [comment]
Hi Rich, 
Someone had created a placeholder for this article a few months back. The more I think about it, the existing Form Rules Overview is functioning more as a reference article. At the same time, I didn't see anything that calls attention to building conditional fields conceptually. Thus, this might serve as an intro.

Justin

**Comment by rbohl** [comment]
@justinchoi001 
In my opinion there's just too much overlap to warrant this article, and it seems neither of us know how the need for it was defined.

The bulk of the article is a brief definition of each rule type, linking to the rule's dedicated article. But we already define the rule actions in a table you included in the [Form Rules Overview](https://learn.liferay.com/dxp/7.x/en/process-automation/forms/user-guide/advanced-forms-usage/form-rules/form-rules-overview.html#form-rule-actions) article:

I recommend reworking this by

1. Extracting whatever intro information you think beneficial from [here](https://github.com/sez11a/liferay-learn/pull/270/files#diff-b3a52c024409c0d9c12a284069b194aca967f67fedf0c52201c37a18ac36a23bR3-R7) and incorporating it into the Form Rules Overview.

2. If helpful to the reader, enhance the definitions that already exist in the Form Rules Overview with the longer ones you've written here.

3. Adding links to the table that go to the existing articles on the rule.


If you've thought about the Forms section flow in detail and you feel strongly that this serves an important role, I'm fine with it going through. I'm just skeptical ;)

**Comment by justinchoi001** [comment]
Hi @rbohl , I consolidated the articles. 
Thanks.

Justin

**Comment by sez11a** [comment]
Superseded by https://github.com/jrhoun/liferay-learn/pull/821

**Pull request closed without merging**
