### PR TITLE
search 7.4 | upgrading search for 7.4 | LRDOCS-9736

### PR DESCRIPTION
**Pull request by rbohl**
Resending after mass conversion of RST > MyST on using-search, including the `ja` section
https://issues.liferay.com/browse/LRDOCS-9736
cc @lipusz

### CODE REVIEW

**Comment by rbohl** [comment]
Japanese translation work requested in [LRDOCS-10017](https://issues.liferay.com/browse/LRDOCS-10017)

**Comment by sez11a** [comment]
@rbohl, this has merge conflicts; please fix. Thanks!

**Comment by rbohl** [comment]
I think it's good now :crossed_fingers:

**Comment by sez11a** [comment]
Whoa that was big. Rebased and pushed, thanks!

**Pull request merged**
