### PR TITLE
LRDOCS-7560 Theme dev batch 1

### PR DESCRIPTION
**Pull request by mwilliams2014**
Finally sending this one back. This supersedes https://github.com/sez11a/liferay-learn/pull/26 and includes updates to the RSTs as well. Note that I did have some trouble with the `site-building\developer-guide\reference\themes\README.rst` . I can't seem to get it to include the referenced :doc:`site-building/developer-guide/reference/themes.rst` file...

### CODE REVIEW

**Comment by mwilliams2014** [comment]
@jrhoun Updating the code examples in this to use the proper template. Will comment here once completed.

**Comment by mwilliams2014** [comment]
@sez11a Code examples updated. Ready for review. Thx!

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by sez11a** [comment]
Superseded by https://github.com/mwilliams2014/liferay-learn/pull/19

**Pull request closed without merging**
