### PR TITLE
Script engine: Use a service tracker if no Util available

### PR DESCRIPTION
**Pull request by jhinkey**
cc @rbohl

### CODE REVIEW

**Comment by sez11a** [comment]
Hey @jhinkey , we aren't linking to HC articles. Even if the article isn't ported yet, please make your best guess as to where it might go; we'll fix the link later.

**Comment by jhinkey** [comment]
@sez11a OK. I updated it to link to a planned article. Thank you.

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by sez11a** [comment]
Superseded by https://github.com/jrhoun/liferay-learn/pull/518

**Pull request closed without merging**
