### PR TITLE
LRDOCS-8150 DXP Workflow XML Dev Tutorial

### PR DESCRIPTION
**Pull request by justinchoi001**

### CODE REVIEW

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by sez11a** [comment]
@justinchoi001 This is merge conflicted; please fix.

**Comment by justinchoi001** [comment]
hi @sez11a , hopefully the merge conflict has been resolved. I pushed up my changes.

**Comment by sez11a** [comment]
@justinchoi001 Still merge conflicted. The two files it's complaining about are the README.rst which we're not using anymore (and thus it can be removed), and using-the-script-engine-in-workflow.md.

**Comment by justinchoi001** [comment]
I've resolved the conflicts by making sure that file is deleted and incorporating the changes to the file.

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by sez11a** [comment]
@justinchoi001 The first two articles here still have Coming Soon content: 

- implementing-workflow.md
- implementing-a-custom-sla-calendar.md

Was this intentional?

**Comment by justinchoi001** [comment]
Hi @sez11a , 
Per our conversation yesterday, I added the two articles as placeholders instead of being just a list on the RST. Secondly, as I was porting the Workflow dev tutorials, I was focused mainly on building workflow definitions and how each node works but the last two articles are unrelated to workflow nodes and workflows in general. We can circle back to them at a later day.

Thanks.
Justin

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by sez11a** [comment]
Superseded by https://github.com/jrhoun/liferay-learn/pull/692

**Pull request closed without merging**
