### PR TITLE
LRDOCS 8473 Customizing Form Layouts

### PR DESCRIPTION
**Pull request by mtokudome**
https://issues.liferay.com/browse/LRDOCS-8473

@sez11a I checked out the functionality on 7.3/7.2, maybe it used to be possible to [adjust the form width itself](https://help.liferay.com/hc/en-us/articles/360017876812-Creating-Advanced-Forms#form-layouts), but I'm not seeing that feature anymore. 

So I just documented [adjusting the width of individual elements](https://help.liferay.com/hc/en-us/articles/360018173991-Styling-Form-Pages) on a form,

### CODE REVIEW

**Comment by sez11a** [comment]
@mtokudome I'm confused; the title of this is Customizing Form Layouts, but I see Asset Library documentation in here....

**Comment by mtokudome** [comment]
> @mtokudome I'm confused; the title of this is Customizing Form Layouts, but I see Asset Library documentation in here....

This article: [Customizing Form Layouts](https://github.com/mtokudome/liferay-learn/blob/lrdocs-8473-customizing-form-layouts/docs/dxp/7.x/en/process-automation/forms/user-guide/advanced-forms-usage/customizing-form-layouts.md) ?

**Comment by sez11a** [comment]
Yes, but what are these other Asset Library documents?

**Comment by rbohl** [comment]
@sez11a I think the commits shown here are mostly in lfieray-learn master. See https://github.com/liferay/liferay-learn/commit/dec5a5d104161ca1288c9893795ac516d971c9c3 and https://github.com/liferay/liferay-learn/commit/cdf0b99d8921d4511da01c218b952c1a1d3dcff5 as examples.

Is it possible updating your fork's master is all that's needed?

**Comment by sez11a** [comment]
Superseded by https://github.com/sez11a/liferay-learn/pull/301

**Pull request closed without merging**
