### PR TITLE
LRDOCS-7953 Fundamentals > Module Projects

### PR DESCRIPTION
**Pull request by jhinkey**
https://issues.liferay.com/browse/LRDOCS-7953

### CODE REVIEW

**Comment by jhinkey** [comment]
I Updated it per the code changes.

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by sez11a** [comment]
Superseded by https://github.com/jhinkey/liferay-learn/pull/24

**Comment by jhinkey** [comment]
Superseded by https://github.com/sez11a/liferay-learn/pull/195

**Pull request closed without merging**
