### PR TITLE
LRDOCS-7542 fragment dev batch 2

### PR DESCRIPTION
**Pull request by mwilliams2014**
@sez11a this includes LRDOCS-7426 (a related User Guide update), LRDOCS-7838, LRDOCS-7921, and LRDOCS-7922 as well.

### CODE REVIEW

**Comment by mwilliams2014** [comment]
@sez11a merge conflict fixed and examples updated. Ready to review.

**Comment by sez11a** [comment]
Hey @mwilliams2014 can you de-conflict this?

**Comment by mwilliams2014** [comment]
Yep. I'll review it in a bit and see what's conflicting.

**Comment by mwilliams2014** [comment]
@sez11a conflict resolved

**Comment by sez11a** [comment]
Just started reviewing :)

**Comment by sez11a** [comment]
Superseded by https://github.com/jrhoun/liferay-learn/pull/551

**Pull request closed without merging**
