### PR TITLE
search 7.x | include backup details in dxp installation guide | LRDOCS-8892

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-8892
cc @jhinkey @lipusz

### CODE REVIEW

**Comment by rbohl** [comment]
This is the commit with the text I changed, @jhinkey @lipusz 

https://github.com/sez11a/liferay-learn/pull/365/commits/7581cdc26d72a2825748a5b583e98888ed9ec0e5

**Comment by lipusz** [comment]
> If you're in a clustered configuration and you're replicating indexes, you must back up each index replica.

We may not necessarily need to get into the details at this level here. Saying something like "follow your search engine's backing-up/snapshotting documentation for backing up a clustered environment" might be enough.

**Comment by rbohl** [comment]
I'll push a commit for these things later :watch: 

1. Remove mention of storing search indexes in the database (unless Jim objects)
2. Refer more generically to backup procedures for the search engine

**Comment by rbohl** [comment]
New commit pushed up. Ready for your review, Rich.

**Comment by jrhoun** [comment]
Reviewing this now.

**Comment by jrhoun** [comment]
Merged. Thanks.

@sez11a you can close this one.

**Pull request closed without merging**
