### PR TITLE
LRDOCS-10532 Add version for Adaptive Media in Commerce

### PR DESCRIPTION
**Pull request by aswinrajeevofficial**
Added Liferay DXP/GA version for Adaptive Media support in Commerce

JIRA: https://issues.liferay.com/browse/LRDOCS-10532

### CODE REVIEW

**Comment by sez11a** [comment]
@aswinrajeevofficial , is there a better way to do this via a badge in one place than by putting the notice in so many places?

**Comment by sez11a** [comment]
@aswinrajeevofficial It just feels weird cluttering up all these articles with a note saying they support Adaptive Media. I think it should be assumed they support this feature, since the normal customer expectation would be that Adaptive Media is supported everywhere.

**Comment by sez11a** [comment]
@aswinrajeevofficial I talked to @jrhoun about this. Here's his suggestion, which I agree with: Maybe it would make sense to put an admonition in the adaptive media docs that says, "As of 7.4 U5+/GA9+, Adaptive Media is available for all Commerce Widgets". And in the Commerce docs, just leave everything as it was with it basically seeing, "Adaptive Media is available OOTB for the following widgets, see Adaptive Media and widget docs for more details"

What do you think?

**Comment by aswinrajeevofficial** [comment]
Understood. Just to clarify, only the Commerce Widgets mentioned support Adaptive Media, not all of them. 

And to confirm whether I've got it correctly, in the Adaptive Media docs, we mention the widgets that support it and in the Commerce docs leave the existing notes as it is without adding the versions.  Is that right?

**Comment by sez11a** [comment]
@aswinrajeevofficial Leave the existing notes as they were before you added the version information. Because the assumption from a customer perspective is that Adaptive Media is supported. That's the natural assumption to make, that we would create Adaptive Media and then the whole product would support it.

**Comment by aswinrajeevofficial** [comment]
Okay got it. So I'll close this PR and mention it on the ticket. Thanks @sez11a @jrhoun

**Pull request closed without merging**
