### PR TITLE
FORMS 7.x | DDMStorageAdapter availability | LRDOCS-7447

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-7447

### CODE REVIEW

**Comment by sez11a** [comment]
Something very weird has happened to this pull. Why are 242 files changed, @rbohl ?

**Comment by rbohl** [comment]
Probably because I updated master?
It's only our commits that differ from master: https://github.com/liferay/liferay-learn/compare/master...rbohl:FORMS_7.x_DDMStorageAdapter-availability_LRDOCS-7447

**Comment by sez11a** [comment]
Pushed this; I'll comment in the other PR.

**Comment by sez11a** [comment]
Merged and pushed forward.

**Pull request merged**
