### PR TITLE
liferay-learn latest | generate rich link previews | LRDOCS-9251

### PR DESCRIPTION
**Pull request by rbohl**
Test adding the sphinxext-opengraph extension to generate rich link previews
https://issues.liferay.com/browse/LRDOCS-9251

### CODE REVIEW

**Comment by sez11a** [comment]
Rebased and pushed.

**Comment by sez11a** [comment]
@rbohl I don't think the ticket referenced above is the correct ticket for this. :-p

**Comment by rbohl** [comment]
Fixed.

Remember, this is something we wanted to test on UAT if possible. I had no way (that I know of) to check it before sending the PR.

cc @jrhoun

**Comment by sez11a** [comment]
Oops. Well, I merged it. @jrhoun, please take note.

**Pull request closed without merging**
