### PR TITLE
liferay-learn buildscript | handle videos | LRDOCS-9006

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-9006

This was necessitated by and includes Jorge's work on https://issues.liferay.com/browse/LRDOCS-8666
cc @jorge-campo

### CODE REVIEW

**Comment by sez11a** [comment]
@rbohl, there's a merge conflict, probably due to the changes from @brianchandotcom.

**Comment by rbohl** [comment]
On it.

**Comment by rbohl** [comment]
Rebased :+1: 

Also, confirmed it works on a single article build with an MP4! :tada:

**Comment by sez11a** [comment]
Rebased and pushed.

**Pull request closed without merging**
